apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-02-17T02:10:35Z"
  labels:
    app: my-nginx
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2021-02-17T02:10:35Z"
  name: my-nginx
  namespace: default
  resourceVersion: "1770852"
  selfLink: /api/v1/namespaces/default/services/my-nginx
  uid: ff7abcc1-568e-49e2-af1e-552f3db725ad
spec:
  clusterIP: 10.107.104.67
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx
  sessionAffinity: None
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
